In [4]:
import numpy as np
from scipy.linalg import inv, solve

# Función para calcular la inversa de una matriz
def calcular_inversa(matriz):
    try:
        return inv(matriz)
    except np.linalg.LinAlgError:
        return "La matriz no es invertible."

# Función para multiplicar dos matrices
def multiplicar_matrices(matriz1, matriz2):
    return np.dot(matriz1, matriz2)

# Función para resolver un sistema de ecuaciones lineales
def resolver_sistema(A, b):
    try:
        return solve(A, b)
    except np.linalg.LinAlgError:
        return "El sistema no tiene solución única."

# Función principal
def main():
    while True:
        print("\nOperaciones con Matrices")
        print("1. Calcular Inversa de una Matriz")
        print("2. Multiplicar dos Matrices")
        print("3. Resolver un Sistema de Ecuaciones Lineales")
        print("4. Salir")
        
        opcion = input("Seleccione una opción: ")
        
        if opcion == '1':
            print("\nCalcular Inversa de una Matriz")
            matriz = []
            n = int(input("Ingrese el tamaño de la matriz (n x n): "))
            for i in range(n):
                fila = list(map(float, input(f"Ingrese la fila {i+1}: ").split()))
                matriz.append(fila)
            matriz = np.array(matriz)
            print("Matriz Inversa:")
            print(calcular_inversa(matriz))
        
        elif opcion == '2':
            print("\nMultiplicar dos Matrices")
            matriz1 = []
            matriz2 = []
            n1, m1 = map(int, input("Ingrese las dimensiones de la primera matriz (n x m): ").split())
            for i in range(n1):
                fila = list(map(float, input(f"Ingrese la fila {i+1} de la primera matriz: ").split()))
                matriz1.append(fila)
            matriz1 = np.array(matriz1)
            
            n2, m2 = map(int, input("Ingrese las dimensiones de la segunda matriz (n x m): ").split())
            for i in range(n2):
                fila = list(map(float, input(f"Ingrese la fila {i+1} de la segunda matriz: ").split()))
                matriz2.append(fila)
            matriz2 = np.array(matriz2)
            
            if m1 != n2:
                print("No se pueden multiplicar las matrices: el número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz.")
            else:
                print("Resultado de la Multiplicación:")
                print(multiplicar_matrices(matriz1, matriz2))
        
        elif opcion == '3':
            print("\nResolver un Sistema de Ecuaciones Lineales")
            A = []
            b = []
            n = int(input("Ingrese el número de ecuaciones (y variables): "))
            print("Ingrese la matriz de coeficientes A:")
            for i in range(n):
                fila = list(map(float, input(f"Ingrese la fila {i+1} de A: ").split()))
                A.append(fila)
            A = np.array(A)
            
            print("Ingrese el vector de términos independientes b:")
            b = list(map(float, input("Ingrese el vector b: ").split()))
            b = np.array(b)
            
            print("Solución del Sistema:")
            print(resolver_sistema(A, b))
        
        elif opcion == '4':
            print("Saliendo del programa...")
            break
        
        else:
            print("Opción no válida. Por favor, seleccione una opción válida.")

# Ejecutar la función principal
main()


Operaciones con Matrices
1. Calcular Inversa de una Matriz
2. Multiplicar dos Matrices
3. Resolver un Sistema de Ecuaciones Lineales
4. Salir


Seleccione una opción:  1



Calcular Inversa de una Matriz


Ingrese el tamaño de la matriz (n x n):  3
Ingrese la fila 1:  2 1 1
Ingrese la fila 2:  1 3 2
Ingrese la fila 3:  1 0 0


Matriz Inversa:
[[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]

Operaciones con Matrices
1. Calcular Inversa de una Matriz
2. Multiplicar dos Matrices
3. Resolver un Sistema de Ecuaciones Lineales
4. Salir


Seleccione una opción:  4


Saliendo del programa...
