Ejercicio 4

In [6]:
import numpy as np
# Crear una matriz
matriz = np.array([[1, 1, 1, 1, 1],
                   [1, 0, 0, 0, 1],
                   [1, 0, 9, 0, 1],
                   [1, 0, 0, 0, 1],
                   [1, 1, 1, 1, 1]])

# Invertir los valores de 9 y 1
matriz[matriz == 9] = 1
matriz[matriz == 1] = 9
print(matriz)

[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 9 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]
