Ejercicio 2

Crea un vector de 10 elementos, siendo los impares 1 y los pares 2.

In [4]:
import numpy as np

# Crear un vector de 10 elementos lleno de ceros
vector = np.zeros(10, dtype=int)

# Asignar 1 a los elementos en posiciones impares
vector[::2] = 1

# Asignar 2 a los elementos en posiciones pares

print(vector)

[1 2 1 2 1 2 1 2 1 2]


Crea un «tablero de ajedrez» 8x8, con 1 en las casillas negras y 0 en las casillas
blancas.

In [5]:
import numpy as np

# Crear un tablero de ajedrez 8x8 lleno de ceros
tablero = np.zeros((8, 8), dtype=int)

# Asignar 1 a las casillas negras (filas y columnas impares)
tablero[1::2, ::2] = 1
tablero[::2, 1::2] = 1

print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
