Ejercicio 1

Crear un array 7x8 lleno de ceros de tipo entero

In [4]:
import numpy as np

# Crear un array 7x8 lleno de ceros de tipo entero
array_7x8 = np.zeros((7, 8), dtype=int)

print(array_7x8)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.

In [5]:
import numpy as np

# Crear un array 7x8 lleno de ceros de tipo entero
array_7x8 = np.zeros((7, 8), dtype=int)

# Cambiar la primera fila a unos
array_7x8[0, :] = 1

print(array_7x8)

[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [6]:
import numpy as np

# Crear un array 7x8 lleno de ceros de tipo entero
array_7x8 = np.zeros((7, 8), dtype=int)

# Asignar a la última fila una secuencia de números del 5 al 12
array_7x8[-1, :] = np.arange(5, 13)

print(array_7x8)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 5  6  7  8  9 10 11 12]]
